# Generated by Django 5.1.4 on 2025-01-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('domain', models.CharField(max_length=255)),
                ('test_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('developer_name', models.CharField(max_length=255)),
                ('developer_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
